# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-18 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Depto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Diocesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.TextField()),
                ('historia', models.TextField()),
                ('imagen', models.ImageField(upload_to='diocesis')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identidad', models.CharField(max_length=15, verbose_name='Numero de Identidad')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('fecha_ord', models.DateField(blank=True, null=True, verbose_name='Fecha de Ordenacion')),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('biografia', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('estado_obispo', models.BooleanField(default=False)),
                ('imagen', models.ImageField(upload_to='empleado')),
                ('sexo', models.CharField(choices=[('1', 'Masculino'), ('2', 'Femenino')], max_length=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Homilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('imagen', models.ImageField(upload_to='parroquia')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.Empleado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Pastoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('encargado', models.CharField(max_length=30)),
                ('horarios', models.CharField(max_length=30)),
                ('eslogan', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='pastorales')),
            ],
            options={
                'verbose_name_plural': 'Pastorales',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('contenido', models.TextField()),
                ('fecha_pub', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicacion')),
                ('imagen', models.ImageField(upload_to='publicaciones')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empleado')),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.AddField(
            model_name='parroquia',
            name='pastoral',
            field=models.ManyToManyField(to='principal.Pastoral'),
        ),
        migrations.AddField(
            model_name='homilia',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Parroquia'),
        ),
        migrations.AddField(
            model_name='diocesi',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empleado'),
        ),
        migrations.AddField(
            model_name='diocesi',
            name='parroquia',
            field=models.ManyToManyField(to='principal.Parroquia'),
        ),
        migrations.AddField(
            model_name='diocesi',
            name='pastoral',
            field=models.ManyToManyField(to='principal.Pastoral'),
        ),
        migrations.AddField(
            model_name='depto',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Municipio'),
        ),
    ]
