# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-25 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20181120_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depto',
            name='municipio',
        ),
        migrations.AddField(
            model_name='depto',
            name='municipio',
            field=models.ManyToManyField(to='principal.Municipio'),
        ),
    ]
