# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-25 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20181125_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Empleado'),
        ),
    ]
