# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-26 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_album_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AddField(
            model_name='album',
            name='imagen',
            field=models.ManyToManyField(to='principal.Imagen'),
        ),
    ]
