# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20181126_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastoral_Diocesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Pastorales_Diocesis',
            },
        ),
        migrations.AlterField(
            model_name='diocesi',
            name='pastoral',
            field=models.ManyToManyField(to='principal.Pastoral_Diocesi'),
        ),
        migrations.AlterField(
            model_name='pastoral',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pastoral_Diocesi'),
        ),
    ]
