# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20181127_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_sacerdote',
            field=models.BooleanField(default=False),
        ),
    ]
