# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20181127_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('lugar', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='estudios',
            field=models.ManyToManyField(to='principal.Estudio'),
        ),
    ]
