# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20181129_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
