# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20181129_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='parroquia',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
