# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-05 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_auto_20181204_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocesi',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
