# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-05 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_diocesi_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocesi',
            name='telefono',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
